#!/bin/bash
set -e
run()  {
	CMD=$1
	echo $CMD
	eval $CMD
	echo "\n"
}

gethDataDir()  {
	NODE_ID=$1
	echo "$GETH_DATA_DIR/$NODE_ID"
}

besuDataDir()  {
	NODE_ID=$1
	echo "$BESU_DATA/$NODE_ID"
}

gethNodeKeyFile()  {
	NODE_ID=$1
	echo "$EIP1559_GETH_NODE_KEY_FILE-$NODE_ID"
}

besuNodeKeyFile()  {
	NODE_ID=$1
	echo "$EIP1559_BESU_NODE_KEY_FILE-$NODE_ID"
}

gethKeyFile()  {
	NODE_ID=$1
	echo "$EIP1559_GETH_ACCOUNT_KEY_FILE-$NODE_ID"
}

gethStaticNodes()  {
	NODE_ID=$1
	echo "$EIP1559_GETH_STATIC_NODES-$NODE_ID.json"
}

gethStaticNodesOut()  {
	NODE_ID=$1
	DATA_DIR=$(gethDataDir $NODE_ID)
	echo "$DATA_DIR/geth/static-nodes.json"
}

gethPwdFile()  {
	NODE_ID=$1
	echo "$EIP1559_GETH_ACCOUNT_PASSWORD-$NODE_ID"
}

getGethLogFile()  {
	NODE_ID=$1
	echo "$EIP1559_GETH_LOGFILE-$NODE_ID"
}

getBesuLogFile()  {
	NODE_ID=$1
	echo "$EIP1559_BESU_LOGFILE-$NODE_ID"
}

runBesu() {
	run "$BESU_PATH $1 --genesis-file=$EIP1559_BESU_GENESIS --data-path=$BESU_DATA --rpc-http-cors-origins=all --discovery-enabled=false --rpc-http-enabled --rpc-http-apis=ETH,NET,WEB3,DEBUG,ADMIN,TRACE,PLUGINS  --p2p-port=30305 --rpc-http-port=8547"
}
